basic.forever(function () {
    cuteBot.moveTime(cuteBot.Direction.left, 50, 5)
    cuteBot.moveTime(cuteBot.Direction.forward, 50, 5)
    cuteBot.moveTime(cuteBot.Direction.right, 50, 5)
})
basic.forever(function () {
    cuteBot.colorLight(cuteBot.RGBLights.ALL, 0xff0000)
    basic.pause(1000)
    cuteBot.colorLight(cuteBot.RGBLights.ALL, 0xb09eff)
    basic.pause(1000)
    cuteBot.colorLight(cuteBot.RGBLights.ALL, 0x00ff00)
    basic.pause(1000)
    cuteBot.colorLight(cuteBot.RGBLights.ALL, 0xff00ff)
    basic.pause(1000)
    cuteBot.colorLight(cuteBot.RGBLights.ALL, 0xff8000)
    basic.pause(1000)
    cuteBot.colorLight(cuteBot.RGBLights.ALL, 0x00ffff)
    basic.pause(1000)
    cuteBot.colorLight(cuteBot.RGBLights.ALL, 0xff0080)
    basic.pause(1000)
    cuteBot.colorLight(cuteBot.RGBLights.ALL, 0x0000ff)
    basic.pause(1000)
    cuteBot.colorLight(cuteBot.RGBLights.ALL, 0xffff00)
    basic.pause(1000)
    cuteBot.colorLight(cuteBot.RGBLights.ALL, 0x7f00ff)
})
basic.forever(function () {
    for (let index = 0; index < 2; index++) {
        music.playTone(196, music.beat(BeatFraction.Whole))
        basic.pause(200)
        music.playTone(196, music.beat(BeatFraction.Half))
        music.playTone(233, music.beat(BeatFraction.Half))
        music.playTone(196, music.beat(BeatFraction.Whole))
        music.playTone(196, music.beat(BeatFraction.Whole))
        music.playTone(196, music.beat(BeatFraction.Whole))
        music.playTone(196, music.beat(BeatFraction.Half))
        music.playTone(233, music.beat(BeatFraction.Half))
        music.playTone(196, music.beat(BeatFraction.Half))
        music.playTone(175, music.beat(BeatFraction.Whole))
    }
    music.playTone(262, music.beat(BeatFraction.Whole))
    basic.pause(200)
    music.playTone(262, music.beat(BeatFraction.Half))
    music.playTone(311, music.beat(BeatFraction.Half))
    music.playTone(262, music.beat(BeatFraction.Whole))
    music.playTone(262, music.beat(BeatFraction.Whole))
    music.playTone(262, music.beat(BeatFraction.Whole))
    music.playTone(262, music.beat(BeatFraction.Half))
    music.playTone(311, music.beat(BeatFraction.Half))
    music.playTone(262, music.beat(BeatFraction.Half))
    music.playTone(233, music.beat(BeatFraction.Whole))
    music.playTone(220, music.beat(BeatFraction.Whole))
    basic.pause(200)
    music.playTone(294, music.beat(BeatFraction.Half))
    music.playTone(370, music.beat(BeatFraction.Half))
    music.playTone(294, music.beat(BeatFraction.Whole))
    music.playTone(294, music.beat(BeatFraction.Double))
    basic.pause(1000)
    for (let index = 0; index < 2; index++) {
        for (let index = 0; index < 3; index++) {
            music.playTone(466, music.beat(BeatFraction.Whole))
            music.playTone(466, music.beat(BeatFraction.Whole))
            basic.pause(100)
            music.playTone(466, music.beat(BeatFraction.Whole))
            music.playTone(466, music.beat(BeatFraction.Whole))
            music.playTone(466, music.beat(BeatFraction.Whole))
            music.playTone(466, music.beat(BeatFraction.Whole))
            music.playTone(392, music.beat(BeatFraction.Half))
            music.playTone(523, music.beat(BeatFraction.Whole))
        }
        music.playTone(440, music.beat(BeatFraction.Whole))
        music.playTone(440, music.beat(BeatFraction.Whole))
        basic.pause(100)
        music.playTone(440, music.beat(BeatFraction.Whole))
        music.playTone(440, music.beat(BeatFraction.Half))
        music.playTone(440, music.beat(BeatFraction.Half))
        music.playTone(392, music.beat(BeatFraction.Half))
        music.playTone(370, music.beat(BeatFraction.Whole))
        basic.pause(1000)
    }
    music.playTone(466, music.beat(BeatFraction.Half))
    music.playTone(466, music.beat(BeatFraction.Half))
    music.playTone(523, music.beat(BeatFraction.Half))
    music.playTone(523, music.beat(BeatFraction.Whole))
    music.playTone(392, music.beat(BeatFraction.Half))
    music.playTone(392, music.beat(BeatFraction.Half))
    music.playTone(466, music.beat(BeatFraction.Half))
    music.playTone(523, music.beat(BeatFraction.Half))
    music.playTone(523, music.beat(BeatFraction.Half))
    music.playTone(466, music.beat(BeatFraction.Half))
    music.playTone(523, music.beat(BeatFraction.Whole))
    music.playTone(392, music.beat(BeatFraction.Half))
    music.playTone(392, music.beat(BeatFraction.Half))
    music.playTone(466, music.beat(BeatFraction.Half))
    music.playTone(523, music.beat(BeatFraction.Half))
    music.playTone(523, music.beat(BeatFraction.Half))
    music.playTone(466, music.beat(BeatFraction.Half))
    music.playTone(587, music.beat(BeatFraction.Whole))
    music.playTone(392, music.beat(BeatFraction.Whole))
    music.playTone(466, music.beat(BeatFraction.Half))
    music.playTone(523, music.beat(BeatFraction.Half))
    music.playTone(523, music.beat(BeatFraction.Half))
    music.playTone(466, music.beat(BeatFraction.Half))
    music.playTone(587, music.beat(BeatFraction.Whole))
    music.playTone(392, music.beat(BeatFraction.Whole))
    basic.pause(500)
    music.playTone(466, music.beat(BeatFraction.Half))
    music.playTone(523, music.beat(BeatFraction.Half))
    music.playTone(698, music.beat(BeatFraction.Whole))
    music.playTone(587, music.beat(BeatFraction.Whole))
    for (let index = 0; index < 3; index++) {
        music.playTone(466, music.beat(BeatFraction.Half))
        music.playTone(523, music.beat(BeatFraction.Half))
        music.playTone(523, music.beat(BeatFraction.Half))
        music.playTone(466, music.beat(BeatFraction.Half))
        music.playTone(698, music.beat(BeatFraction.Whole))
        music.playTone(587, music.beat(BeatFraction.Whole))
    }
    basic.pause(500)
    music.playTone(523, music.beat(BeatFraction.Half))
    music.playTone(466, music.beat(BeatFraction.Half))
    music.playTone(440, music.beat(BeatFraction.Double))
    music.playTone(392, music.beat(BeatFraction.Double))
    basic.pause(500)
    for (let index = 0; index < 3; index++) {
        music.playTone(392, music.beat(BeatFraction.Half))
        music.playTone(587, music.beat(BeatFraction.Half))
        basic.pause(100)
        music.playTone(392, music.beat(BeatFraction.Half))
        music.playTone(554, music.beat(BeatFraction.Half))
        music.playTone(587, music.beat(BeatFraction.Half))
        music.playTone(554, music.beat(BeatFraction.Half))
        music.playTone(466, music.beat(BeatFraction.Half))
    }
    basic.pause(200)
    music.playTone(587, music.beat(BeatFraction.Half))
    music.playTone(554, music.beat(BeatFraction.Half))
    music.playTone(587, music.beat(BeatFraction.Half))
    music.playTone(554, music.beat(BeatFraction.Half))
    music.playTone(587, music.beat(BeatFraction.Half))
    music.playTone(523, music.beat(BeatFraction.Half))
    music.playTone(466, music.beat(BeatFraction.Half))
    music.playTone(311, music.beat(BeatFraction.Double))
    music.playTone(392, music.beat(BeatFraction.Double))
    music.playTone(262, music.beat(BeatFraction.Half))
    music.playTone(370, music.beat(BeatFraction.Half))
    music.playTone(392, music.beat(BeatFraction.Half))
    music.playTone(370, music.beat(BeatFraction.Half))
    music.playTone(311, music.beat(BeatFraction.Half))
    music.playTone(294, music.beat(BeatFraction.Half))
    music.playTone(440, music.beat(BeatFraction.Half))
    basic.pause(200)
    music.playTone(294, music.beat(BeatFraction.Half))
    music.playTone(440, music.beat(BeatFraction.Half))
    music.playTone(294, music.beat(BeatFraction.Half))
    basic.pause(500)
    music.playTone(262, music.beat(BeatFraction.Whole))
    music.playTone(262, music.beat(BeatFraction.Whole))
    music.playTone(262, music.beat(BeatFraction.Double))
})
